# Generated by Django 5.0.6 on 2024-07-09 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_shipmenttracking_uztracking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uztracking',
            old_name='customer_code',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='uztracking',
            old_name='shipment_tracking_code',
            new_name='tracking_code',
        ),
    ]
