# Generated by Django 5.0.6 on 2024-07-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_shipmenttracking_flight_uztracking_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmenttracking',
            name='flight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uztracking',
            name='flight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
